import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export const metadata = {
  title: "Terms of Service — AlphoGenAI",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen px-4 py-16">
      <div className="mx-auto max-w-3xl">
        <Link
          href="/"
          className="mb-8 inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"
        >
          <ArrowLeft className="h-4 w-4" />
          Back
        </Link>

        <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-8">
          Last updated: April 17, 2026
        </p>

        <div className="prose prose-invert prose-sm max-w-none space-y-6 text-muted-foreground">
          <section>
            <h2 className="text-lg font-semibold text-foreground">1. Acceptance of Terms</h2>
            <p>
              By accessing or using AlphoGenAI (&quot;the Service&quot;), operated by AlphoGen
              (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;), you agree to be bound by these Terms of Service.
              If you do not agree, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">2. Description of Service</h2>
            <p>
              AlphoGenAI is an AI-powered video generation platform that allows users to create
              videos from text prompts, images, and reference media using artificial intelligence
              models. The Service includes video generation, social media export, and publishing
              features.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">3. User Accounts</h2>
            <p>
              You must create an account to use the Service. You are responsible for maintaining
              the security of your account credentials. You must be at least 18 years old to use
              the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">4. Subscription Plans</h2>
            <p>
              The Service offers Free, Pro, and Premium subscription tiers. Paid subscriptions
              are billed monthly via Stripe. You may cancel your subscription at any time.
              Refunds are handled on a case-by-case basis.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">5. Content Ownership</h2>
            <p>
              You retain ownership of the prompts and reference media you provide. Videos
              generated by the Service are licensed to you for personal and commercial use,
              subject to the terms of the underlying AI models (ByteDance Seedance, Wan 2.2).
              You are responsible for ensuring your use complies with applicable laws.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">6. Prohibited Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Generate content that is illegal, harmful, or violates third-party rights</li>
              <li>Generate deepfakes or non-consensual intimate imagery</li>
              <li>Attempt to bypass usage limits or security measures</li>
              <li>Resell or redistribute the Service without authorization</li>
              <li>Use the Service to generate spam or misleading content</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">7. Third-Party Integrations</h2>
            <p>
              The Service integrates with third-party platforms (YouTube, TikTok, Instagram)
              for video publishing. When you connect your social media accounts, you authorize
              AlphoGenAI to upload content on your behalf. You may disconnect at any time.
              We do not access your social media data beyond what is necessary for publishing.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">8. AI-Generated Content Disclaimer</h2>
            <p>
              Videos are generated by AI models and may not always produce expected results.
              We do not guarantee the quality, accuracy, or appropriateness of generated content.
              You are solely responsible for reviewing content before publishing.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">9. Service Availability</h2>
            <p>
              We strive for high availability but do not guarantee uninterrupted service.
              We may modify, suspend, or discontinue features at any time with reasonable notice.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">10. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, AlphoGen shall not be liable for any
              indirect, incidental, special, or consequential damages arising from your use
              of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">11. Changes to Terms</h2>
            <p>
              We may update these Terms from time to time. Continued use of the Service after
              changes constitutes acceptance of the updated Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground">12. Contact</h2>
            <p>
              For questions about these Terms, contact us at{" "}
              <a href="mailto:contact@alphogen.com" className="text-primary hover:underline">
                contact@alphogen.com
              </a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
