/** Measured production inputs used for provider-aware routing and estimates. */
export const HEYGEN_ESTIMATED_USD_PER_OUTPUT_SECOND = 0.04;
export const LATENTSYNC_MAX_INPUT_SECONDS = 8;
export const LATENTSYNC_MAX_CONCURRENT_JOBS = 2;
export const MODAL_A10_GPU_USD_PER_SECOND = 0.000306;
export const LATENTSYNC_MEASURED_OUTPUT_SECONDS = 28.36;
export const LATENTSYNC_MEASURED_ELAPSED_SECONDS = 1063.25;
export const LATENTSYNC_MEASURED_USD_PER_OUTPUT_SECOND =
  (LATENTSYNC_MEASURED_ELAPSED_SECONDS * MODAL_A10_GPU_USD_PER_SECOND) /
  LATENTSYNC_MEASURED_OUTPUT_SECONDS;
